# Generated by Django 3.2.5 on 2021-07-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacker_id', models.IntegerField(unique=True)),
                ('time', models.TimeField(null=True)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=10)),
                ('hn_deleted', models.BooleanField(null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('text', models.CharField(max_length=5000, null=True)),
                ('url', models.URLField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('local', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='core.base')),
            ],
        ),
    ]
