# Generated by Django 3.2.5 on 2021-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210726_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='hacker_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='synced',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
