# Generated by Django 3.2.5 on 2021-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210727_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
